declare const styles: {
  readonly summaryCard: string;
  readonly imageWrapper: string;
  readonly imageSection: string;
  readonly imageSingle: string;
  readonly imageGrid: string;
  readonly imageGridItem: string;
  readonly contentSection: string;
  readonly titleRow: string;
  readonly titleGroup: string;
  readonly title: string;
  readonly subtitle: string;
  readonly badge: string;
  readonly description: string;
  readonly descriptionSkeleton: string;
  readonly metadata: string;
  readonly metadataItem: string;
  readonly customIcon: string;
  readonly metadataSeparator: string;
  readonly buttonSection: string;
  readonly button: string;
  readonly buttonSkeletonWrapper: string;
  readonly overflowIndicator: string;
  readonly loadingContainer: string;
  readonly skeletonImageContainer: string;
  readonly visuallyHidden: string;
  readonly errorContainer: string;
  readonly emptyContainer: string;
  readonly emptyState: string;
  readonly emptyTitle: string;
  readonly emptyMessage: string;
  readonly topOverlay: string;
};

export default styles;
